project_id = "ocfjtvrjkhwyxhphovsf"

[functions.generate-proposal]
verify_jwt = false

[functions.generate-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-asaas-checkout]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.get-deliverable-url]
verify_jwt = false
